" Name:         manku
" Author:       Jason Chrosrova <jason.chrosrova@icloud.com>
" Maintainer:   Jason Chrosrova <jason.chrosrova@icloud.com>
" License:      Vim License (see `:help license`)
" Last Updated: Fri Jun  2 10:46:29 2023

" Generated by Colortemplate v2.2.0

set background=dark

hi clear
let g:colors_name = 'manku'

let s:t_Co = exists('&t_Co') && !has('gui_running') ? +&t_Co : -1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#18151c', '#ff5c8f', '#79dcaa', '#99895e', '#12428d', '#e02c6d', '#0aaeb3', '#d4d4d5', '#2b2b2b', '#f87070', '#98b783', '#ffe5ce', '#1f6feb', '#ff5c8f', '#52de97', '#ffffff']
endif
if has('nvim')
  let g:terminal_color_0 = '#18151c'
  let g:terminal_color_1 = '#ff5c8f'
  let g:terminal_color_2 = '#79dcaa'
  let g:terminal_color_3 = '#99895e'
  let g:terminal_color_4 = '#12428d'
  let g:terminal_color_5 = '#e02c6d'
  let g:terminal_color_6 = '#0aaeb3'
  let g:terminal_color_7 = '#d4d4d5'
  let g:terminal_color_8 = '#2b2b2b'
  let g:terminal_color_9 = '#f87070'
  let g:terminal_color_10 = '#98b783'
  let g:terminal_color_11 = '#ffe5ce'
  let g:terminal_color_12 = '#1f6feb'
  let g:terminal_color_13 = '#ff5c8f'
  let g:terminal_color_14 = '#52de97'
  let g:terminal_color_15 = '#ffffff'
endif
hi Normal guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
if exists('g:manku_emphasis_color_list')
  unlet g:manku_emphasis_color_list
endif
const g:manku_emphasis_color_list = ['blue', 'red', 'purple', 'orange', 'silver', 'green', 'azure', 'pink']
func! s:emphasis(c) abort
  let c = type(a:c) == type('') ? a:c : 'white'
  if c ==? 'random'
    if !exists('*rand') || !exists('*srand')
      echoerr 'The "random" color cannot be used since your Vim is too old.'
    else
      if !exists('s:eed')
        let s:eed = srand()
      endif
      let pick = rand(s:eed) % (len(g:manku_emphasis_color_list) + 1)
      let c = get(g:manku_emphasis_color_list, pick, 'white')
    endif
  endif
  return c
endfunction
let s:_emphasis = s:emphasis(get(g:, 'manku_emphasis_color'))
if s:_emphasis ==? 'blue'
  hi mankuEmphasis guifg=#009ffd guibg=NONE gui=NONE cterm=NONE
elseif s:_emphasis ==? 'red'
  hi mankuEmphasis guifg=#ff101f guibg=NONE gui=NONE cterm=NONE
elseif s:_emphasis ==? 'purple'
  hi mankuEmphasis guifg=#dc6acf guibg=NONE gui=NONE cterm=NONE
elseif s:_emphasis ==? 'orange'
  hi mankuEmphasis guifg=#ff6700 guibg=NONE gui=NONE cterm=NONE
elseif s:_emphasis ==? 'silver'
  hi mankuEmphasis guifg=#736f72 guibg=NONE gui=NONE cterm=NONE
elseif s:_emphasis ==? 'green'
  hi mankuEmphasis guifg=#109648 guibg=NONE gui=NONE cterm=NONE
elseif s:_emphasis ==? 'azure'
  hi mankuEmphasis guifg=#2a9d8f guibg=NONE gui=NONE cterm=NONE
elseif s:_emphasis ==? 'pink'
  hi mankuEmphasis guifg=#ef626c guibg=NONE gui=NONE cterm=NONE
else
  hi mankuEmphasis guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
endif
hi QuickScopePrimary guifg=#ff5f00 guibg=NONE gui=NONE cterm=NONE
hi QuickScopeSecondary guifg=#e02c6d guibg=NONE gui=NONE cterm=NONE
hi mankuStrong guifg=#ffffff guibg=NONE gui=bold cterm=bold
hi! link Boolean mankuEmphasis
hi CursorColumn guibg=#23242a gui=NONE cterm=NONE
hi CursorLine guibg=#23242a gui=NONE cterm=NONE
hi ColorColumn guifg=NONE guibg=#323232 gui=NONE cterm=NONE
hi Comment guifg=#ffe5ce guibg=NONE gui=NONE cterm=NONE
hi Conceal guifg=#18151c guibg=NONE gui=NONE cterm=NONE
hi! link Constant Normal
hi Cursor guifg=#18151c guibg=#d4d4d5 gui=NONE cterm=NONE
hi CursorLineNr guifg=#d4d4d5 guibg=#2b2b2b gui=NONE cterm=NONE
hi DiffAdd guifg=NONE guibg=#12428d gui=NONE cterm=NONE
hi DiffChange guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi DiffDelete guifg=NONE guibg=#f87070 gui=NONE cterm=NONE
hi DiffText guifg=NONE guibg=#99895e gui=NONE cterm=NONE
hi Directory guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi EndOfBuffer guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#18151c guibg=#f87070 gui=NONE cterm=NONE
hi! link ErrorMsg Error
hi FoldColumn guifg=#d4d4d5 guibg=#2b2b2b gui=NONE cterm=NONE
hi! link Folded FoldColumn
hi Identifier guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi IncSearch guifg=#ffe5ce guibg=#666666 gui=NONE cterm=NONE
hi LineNr guifg=#666666 guibg=NONE gui=NONE cterm=NONE
hi MatchParen guifg=#18151c guibg=#666666 gui=NONE cterm=NONE
hi ModeMsg guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#666666 guibg=NONE gui=NONE cterm=NONE
hi! link Operator Normal
hi Pmenu guifg=#d4d4d5 guibg=#323232 gui=NONE cterm=NONE
hi PmenuSbar guifg=#18151c guibg=#2b2b2b gui=NONE cterm=NONE
hi! link PmenuSel Cursor
hi! link PmenuThumb Cursor
hi PreProc guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi! link Include mankuEmphasis
hi! link Define mankuEmphasis
hi! link PreCondit mankuEmphasis
hi Question guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi Search guifg=#ffe5ce guibg=#666666 gui=NONE cterm=NONE
hi SignColumn guifg=#2b2b2b guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi SpecialKey guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi String guifg=#98b783 guibg=NONE gui=NONE cterm=NONE
hi SpellBad guifg=#f87070 guibg=NONE gui=undercurl cterm=undercurl
hi SpellCap guifg=#1f6feb guibg=NONE gui=undercurl cterm=undercurl
hi SpellLocal guifg=#f87070 guibg=NONE gui=undercurl cterm=undercurl
hi SpellRare guifg=#ffe5ce guibg=NONE gui=undercurl cterm=undercurl
hi! link Statement mankuEmphasis
hi! link Keyword mankuEmphasis
hi StatusLine guifg=#d4d4d5 guibg=#23242a gui=NONE cterm=NONE
hi StatusLineNC guifg=#d4d4d5 guibg=#666666 gui=NONE cterm=NONE
hi TabLine guifg=#d4d4d5 guibg=#23242a gui=NONE cterm=NONE
hi Title guifg=#666666 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#1f6feb guibg=NONE gui=NONE cterm=NONE
hi! link Type Normal
hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=NONE
hi VertSplit guifg=#323232 guibg=NONE gui=NONE cterm=NONE
hi WinSeparator guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Visual guifg=NONE guibg=#323232 gui=NONE cterm=NONE
hi VisualNOS guifg=#2b2b2b guibg=#d4d4d5 gui=NONE cterm=NONE
hi WarningMsg guifg=#ffe5ce guibg=NONE gui=NONE cterm=NONE
hi WildMenu guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi TSAttribute guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi TSCharacter guifg=#98b783 guibg=NONE gui=NONE cterm=NONE
hi TSCharacterSpecial guifg=#f87070 guibg=NONE gui=NONE cterm=NONE
hi! link TSConstant Normal
hi! link TSConstBuiltin mankuEmphasis
hi! link TSConstMacro mankuEmphasis
hi TSDebug guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi TSDefine guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi! link TSException mankuEmphasis
hi! link TSKeywordOperator Keyword
hi! link TSStorageClass Keyword
hi! link TSString String
hi TSStringRegex guifg=#f87070 guibg=NONE gui=NONE cterm=NONE
hi TSStringEscape guifg=#ffe5ce guibg=NONE gui=NONE cterm=NONE
hi TSStringSpecial guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi! link TSSymbol mankuEmphasis
hi TSTagAttribute guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi TSText guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi TSStrong guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi! link TSEmphasis TSStrong
hi TSURI guifg=#1f6feb guibg=NONE gui=underline cterm=NONE
hi TSEnvironmentName guifg=#79dcaa guibg=NONE gui=NONE cterm=NONE
hi TSVariable guifg=#d4d4d5 guibg=NONE gui=NONE cterm=NONE
hi! link TSVariableBuiltin Normal
hi TSAssignment guifg=#52de97 guibg=NONE gui=bold cterm=bold
hi! link TSKeyword Keyword
hi! link TSKeywordReturn Keyword
hi helpHyperTextJump guifg=#0aaeb3 guibg=NONE gui=NONE cterm=NONE
hi helpHeader guifg=#ff5c8f guibg=NONE gui=NONE cterm=NONE
hi gitCommitFirstLine guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi! link gitCommitSummary mankuEmphasis
hi gitCommitOverflow guifg=#f87070 guibg=NONE gui=undercurl cterm=undercurl
hi! link fugitiveUntrackedHeading mankuStrong
hi! link fugitiveUntrackedModifier mankuStrong
hi! link fugitiveUnstagedHeading mankuStrong
hi! link fugitiveUnstagedModifier mankuStrong
hi! link fugitiveStagedHeading mankuStrong
hi! link fugitiveStagedModifier mankuStrong
hi! link fugitiveHeader mankuStrong
hi fugitiveCount guifg=#98b783 guibg=NONE gui=NONE cterm=NONE
hi! link diffLine mankuEmphasis
hi diffRemoved guifg=#f87070 guibg=NONE gui=NONE cterm=NONE
hi diffAdded guifg=#1f6feb guibg=NONE gui=NONE cterm=NONE
hi! link plugDeleted diffRemoved
hi! link sqlKeyword Keyword
hi! link sqlFunction Keyword
hi! link sqlSpecial Keyword
hi! link xmlTagName Keyword
hi! link lispDecl Normal
hi! link lispFunc Normal
hi! link lispVar Normal
hi! link lispKey Keyword
hi! link swiftFuncDefinition Keyword
hi anyDiceTSFunction guifg=#ff5c8f guibg=NONE gui=NONE cterm=NONE
hi anyDiceTSParameter guifg=#0aaeb3 guibg=NONE gui=NONE cterm=NONE
hi Italic gui=italic cterm=italic
if !s:italics
  hi Italic gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  hi Normal ctermfg=188 ctermbg=NONE cterm=NONE
  if exists('g:manku_emphasis_color_list')
    unlet g:manku_emphasis_color_list
  endif
  const g:manku_emphasis_color_list = ['blue', 'red', 'purple', 'orange', 'silver', 'green', 'azure', 'pink']
  func! s:emphasis(c) abort
    let c = type(a:c) == type('') ? a:c : 'white'
    if c ==? 'random'
      if !exists('*rand') || !exists('*srand')
        echoerr 'The "random" color cannot be used since your Vim is too old.'
      else
        if !exists('s:eed')
          let s:eed = srand()
        endif
        let pick = rand(s:eed) % (len(g:manku_emphasis_color_list) + 1)
        let c = get(g:manku_emphasis_color_list, pick, 'white')
      endif
    endif
    return c
  endfunction
  let s:_emphasis = s:emphasis(get(g:, 'manku_emphasis_color'))
  if s:_emphasis ==? 'blue'
    hi mankuEmphasis ctermfg=75 ctermbg=NONE cterm=NONE
  elseif s:_emphasis ==? 'red'
    hi mankuEmphasis ctermfg=196 ctermbg=NONE cterm=NONE
  elseif s:_emphasis ==? 'purple'
    hi mankuEmphasis ctermfg=170 ctermbg=NONE cterm=NONE
  elseif s:_emphasis ==? 'orange'
    hi mankuEmphasis ctermfg=202 ctermbg=NONE cterm=NONE
  elseif s:_emphasis ==? 'silver'
    hi mankuEmphasis ctermfg=242 ctermbg=NONE cterm=NONE
  elseif s:_emphasis ==? 'green'
    hi mankuEmphasis ctermfg=35 ctermbg=NONE cterm=NONE
  elseif s:_emphasis ==? 'azure'
    hi mankuEmphasis ctermfg=37 ctermbg=NONE cterm=NONE
  elseif s:_emphasis ==? 'pink'
    hi mankuEmphasis ctermfg=203 ctermbg=NONE cterm=NONE
  else
    hi mankuEmphasis ctermfg=231 ctermbg=NONE cterm=NONE
  endif
  hi QuickScopePrimary ctermfg=202 ctermbg=NONE cterm=NONE
  hi QuickScopeSecondary ctermfg=161 ctermbg=NONE cterm=NONE
  hi mankuStrong ctermfg=231 ctermbg=NONE cterm=bold
  hi! link Boolean mankuEmphasis
  hi CursorColumn ctermbg=235 cterm=NONE
  hi CursorLine ctermbg=235 cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi Comment ctermfg=223 ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=233 ctermbg=NONE cterm=NONE
  hi! link Constant Normal
  hi Cursor ctermfg=233 ctermbg=188 cterm=NONE
  hi CursorLineNr ctermfg=188 ctermbg=235 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=25 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=203 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=101 cterm=NONE
  hi Directory ctermfg=188 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=188 ctermbg=NONE cterm=NONE
  hi Error ctermfg=233 ctermbg=203 cterm=NONE
  hi! link ErrorMsg Error
  hi FoldColumn ctermfg=188 ctermbg=235 cterm=NONE
  hi! link Folded FoldColumn
  hi Identifier ctermfg=188 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=223 ctermbg=241 cterm=NONE
  hi LineNr ctermfg=241 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=233 ctermbg=241 cterm=NONE
  hi ModeMsg ctermfg=188 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=241 ctermbg=NONE cterm=NONE
  hi! link Operator Normal
  hi Pmenu ctermfg=188 ctermbg=236 cterm=NONE
  hi PmenuSbar ctermfg=233 ctermbg=235 cterm=NONE
  hi! link PmenuSel Cursor
  hi! link PmenuThumb Cursor
  hi PreProc ctermfg=188 ctermbg=NONE cterm=NONE
  hi! link Include mankuEmphasis
  hi! link Define mankuEmphasis
  hi! link PreCondit mankuEmphasis
  hi Question ctermfg=188 ctermbg=NONE cterm=NONE
  hi Search ctermfg=223 ctermbg=241 cterm=NONE
  hi SignColumn ctermfg=235 ctermbg=NONE cterm=NONE
  hi Special ctermfg=188 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=188 ctermbg=NONE cterm=NONE
  hi String ctermfg=108 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=203 ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=26 ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=203 ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=223 ctermbg=NONE cterm=undercurl
  hi! link Statement mankuEmphasis
  hi! link Keyword mankuEmphasis
  hi StatusLine ctermfg=188 ctermbg=235 cterm=NONE
  hi StatusLineNC ctermfg=188 ctermbg=241 cterm=NONE
  hi TabLine ctermfg=188 ctermbg=235 cterm=NONE
  hi Title ctermfg=241 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=26 ctermbg=NONE cterm=NONE
  hi! link Type Normal
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=236 ctermbg=NONE cterm=NONE
  hi WinSeparator ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=236 cterm=NONE
  hi VisualNOS ctermfg=235 ctermbg=188 cterm=NONE
  hi WarningMsg ctermfg=223 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=188 ctermbg=NONE cterm=NONE
  hi TSAttribute ctermfg=188 ctermbg=NONE cterm=NONE
  hi TSCharacter ctermfg=108 ctermbg=NONE cterm=NONE
  hi TSCharacterSpecial ctermfg=203 ctermbg=NONE cterm=NONE
  hi! link TSConstant Normal
  hi! link TSConstBuiltin mankuEmphasis
  hi! link TSConstMacro mankuEmphasis
  hi TSDebug ctermfg=188 ctermbg=NONE cterm=NONE
  hi TSDefine ctermfg=188 ctermbg=NONE cterm=NONE
  hi! link TSException mankuEmphasis
  hi! link TSKeywordOperator Keyword
  hi! link TSStorageClass Keyword
  hi! link TSString String
  hi TSStringRegex ctermfg=203 ctermbg=NONE cterm=NONE
  hi TSStringEscape ctermfg=223 ctermbg=NONE cterm=NONE
  hi TSStringSpecial ctermfg=188 ctermbg=NONE cterm=NONE
  hi! link TSSymbol mankuEmphasis
  hi TSTagAttribute ctermfg=188 ctermbg=NONE cterm=NONE
  hi TSText ctermfg=188 ctermbg=NONE cterm=NONE
  hi TSStrong ctermfg=NONE ctermbg=NONE cterm=bold
  hi! link TSEmphasis TSStrong
  hi TSURI ctermfg=26 ctermbg=NONE cterm=NONE
  hi TSEnvironmentName ctermfg=115 ctermbg=NONE cterm=NONE
  hi TSVariable ctermfg=188 ctermbg=NONE cterm=NONE
  hi! link TSVariableBuiltin Normal
  hi TSAssignment ctermfg=78 ctermbg=NONE cterm=bold
  hi! link TSKeyword Keyword
  hi! link TSKeywordReturn Keyword
  hi helpHyperTextJump ctermfg=37 ctermbg=NONE cterm=NONE
  hi helpHeader ctermfg=204 ctermbg=NONE cterm=NONE
  hi gitCommitFirstLine ctermfg=NONE ctermbg=NONE cterm=bold
  hi! link gitCommitSummary mankuEmphasis
  hi gitCommitOverflow ctermfg=203 ctermbg=NONE cterm=undercurl
  hi! link fugitiveUntrackedHeading mankuStrong
  hi! link fugitiveUntrackedModifier mankuStrong
  hi! link fugitiveUnstagedHeading mankuStrong
  hi! link fugitiveUnstagedModifier mankuStrong
  hi! link fugitiveStagedHeading mankuStrong
  hi! link fugitiveStagedModifier mankuStrong
  hi! link fugitiveHeader mankuStrong
  hi fugitiveCount ctermfg=108 ctermbg=NONE cterm=NONE
  hi! link diffLine mankuEmphasis
  hi diffRemoved ctermfg=203 ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=26 ctermbg=NONE cterm=NONE
  hi! link plugDeleted diffRemoved
  hi! link sqlKeyword Keyword
  hi! link sqlFunction Keyword
  hi! link sqlSpecial Keyword
  hi! link xmlTagName Keyword
  hi! link lispDecl Normal
  hi! link lispFunc Normal
  hi! link lispVar Normal
  hi! link lispKey Keyword
  hi! link swiftFuncDefinition Keyword
  hi anyDiceTSFunction ctermfg=204 ctermbg=NONE cterm=NONE
  hi anyDiceTSParameter ctermfg=37 ctermbg=NONE cterm=NONE
  hi Italic cterm=italic
  if !s:italics
    hi Italic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: light #D4D4D5 ~
" Color: white #FFFFFF ~
" Color: dark #18151c ~
" Color: gray0 #666666 ~
" Color: gray1 #323232 ~
" Color: gray2 #23242a ~
" Color: gray3 #2b2b2b ~
" Color: lime #98B783 ~
" Color: yellow #FFE5CE ~
" Color: darkyellow #99895E ~
" Color: green #79DCAA ~
" Color: red #F87070 ~
" Color: pink #FF5C8F ~
" Color: orange #FF5F00 ~
" Color: blue #1F6FEB ~
" Color: darkblue #12428D ~
" Color: magenta #E02C6D ~
" Color: lightmagenta #FF5C8F ~
" Color: cyan #52DE97 ~
" Color: darkcyan #0AAEB3 ~
" Color: emphasisBlue #009FFD ~
" Color: emphasisRed #FF101F ~
" Color: emphasisOrange #FF6700 ~
" Color: emphasisPurple #DC6ACF ~
" Color: emphasisSilver #736F72 ~
" Color: emphasisGreen #109648 ~
" Color: emphasisAzure #2A9D8F ~
" Color: emphasisPink #EF626C ~
" Term colors: dark  pink green darkyellow darkblue magenta      darkcyan  light
" Term colors: gray3 red  lime  yellow     blue     lightmagenta cyan white
" vim: et ts=2 sw=2
